name: Steam Watch Report

on:
  schedule:
    - cron: "40 0 * * *"
  workflow_dispatch:
  push:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ste-xx/steam-price-action@main
        with:
          profileId: ${{secrets.profileId}}
          productNameMapping: |
            Weird West: Definitive Edition | weird west
            Darkest Dungeon® II            | darkest dungeon 2
            
        id: price
      - run: echo "${{ steps.price.outputs.tsv }}" > report.tsv
      - run: echo "$DATA" > report.json
        env:
          DATA: ${{ steps.price.outputs.rawJson }}
          
      - uses: EndBug/add-and-commit@v9
        with:
          add: report.tsv report.json
