name: Steam Watch Report

on:
  schedule:
    - cron: "40 0 * * *"
  workflow_dispatch:
  push:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      ${{secrets.profileId}}
     

      
      
      - uses: ste-xx/steam-price-action@v1
        with:
          profileId: ${{secrets.profileId}}
        id: price
      - run: echo "${{ steps.price.outputs.tsv }}" > report.tsv
      - uses: EndBug/add-and-commit@v9
        with:
          add: report.tsv
