name: Steam Watch Report

on:
  schedule:
    - cron: "40 0 * * *"
  workflow_dispatch:
  push:

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ste-xx/steam-price-action@v1
        with:
          input: | 
            [
              { "productId": "45401", "label": "Pathfinder: Wrath of the Righteous" },
              { "productId": "104326", "label": "Heros hour" },
              { "productId": "84981", "label": "Wartales" },
              { "productId": "56714", "label": "Solasta" },
              { "productId": "29228", "label": "Song of Conquest" },
              { "productId": "62170", "label": "King Arthur"},
              { "productId": "55450", "label": "The Iron Oath"},
              { "productId": "48637", "label": "The last spell"},
              { "productId": "71707", "label": "Weird West" },
              { "productId": "110185", "label": "Hard West 2"},
              { "productId": "61602", "label": "Tainted Grail: Conquest"}
            ]
        id: price
      - run: echo "${{ steps.price.outputs.tsv }}" > report.tsv
      - uses: EndBug/add-and-commit@v9
        with:
          add: report.tsv
